name: External Events
on:
  repository_dispatch:
    types: [build]
run-name: "Start by @${{github.actor}}"
jobs:
  echo-a-string:
    runs-on: ubuntu-latest
    steps:
       - run: echo ${{ github.event.client_payload.env}}     